/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */

package simrskhanza;

/**
 *
 * @author perpustakaan
 */
public class DlgAbout extends javax.swing.JDialog {

    
    public DlgAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10,10);
        setSize(465,515);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        jLabel16 = new javax.swing.JLabel();
        panelGlass4 = new usu.widget.glass.PanelGlass();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        panelGlass5 = new usu.widget.glass.PanelGlass();
        panelGlass6 = new usu.widget.glass.PanelGlass();
        panelGlass7 = new usu.widget.glass.PanelGlass();
        panelGlass8 = new usu.widget.glass.PanelGlass();
        BtnKeluar = new widget.Button();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        panelGlass9 = new usu.widget.glass.PanelGlass();
        panelGlass10 = new usu.widget.glass.PanelGlass();
        panelGlass11 = new usu.widget.glass.PanelGlass();
        panelGlass12 = new usu.widget.glass.PanelGlass();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("::[ About Program ]::");
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ About Program ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(50, 50, 50));
        jLabel16.setText(".: Developer");
        jLabel16.setName("jLabel16"); // NOI18N
        internalFrame1.add(jLabel16);
        jLabel16.setBounds(10, 30, 110, 20);

        panelGlass4.setBackground(new java.awt.Color(235, 255, 235));
        panelGlass4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 246, 236)));
        panelGlass4.setOpaqueImage(false);
        panelGlass4.setRound(false);
        panelGlass4.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(50, 50, 50));
        jLabel19.setText("RS Permata Medika Kebumen, RS Handayani Lampung Utara, ");
        jLabel19.setName("jLabel19"); // NOI18N
        panelGlass4.add(jLabel19);
        jLabel19.setBounds(126, 160, 320, 14);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(50, 50, 50));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Blog :");
        jLabel24.setName("jLabel24"); // NOI18N
        panelGlass4.add(jLabel24);
        jLabel24.setBounds(0, 30, 55, 14);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(50, 50, 50));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Phone :");
        jLabel20.setName("jLabel20"); // NOI18N
        panelGlass4.add(jLabel20);
        jLabel20.setBounds(0, 10, 55, 14);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(50, 50, 50));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Email :");
        jLabel21.setName("jLabel21"); // NOI18N
        panelGlass4.add(jLabel21);
        jLabel21.setBounds(0, 50, 55, 14);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(50, 50, 50));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Github :");
        jLabel22.setName("jLabel22"); // NOI18N
        panelGlass4.add(jLabel22);
        jLabel22.setBounds(0, 70, 55, 14);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(50, 50, 50));
        jLabel23.setText("Kontributor & Donatur : RS Jeumpa Pontianak Kalimantan Barat, RS Sadewa Yogyakarta,");
        jLabel23.setName("jLabel23"); // NOI18N
        panelGlass4.add(jLabel23);
        jLabel23.setBounds(10, 100, 440, 14);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(50, 50, 50));
        jLabel25.setText("RS Puri Husada Sleman Yogyakarta, RS Pelita Insani Martapura,");
        jLabel25.setName("jLabel25"); // NOI18N
        panelGlass4.add(jLabel25);
        jLabel25.setBounds(126, 120, 320, 14);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(50, 50, 50));
        jLabel26.setText("RS Assyifa Manna, RS Arvita Bunda Sleman Yogyakarta,");
        jLabel26.setName("jLabel26"); // NOI18N
        panelGlass4.add(jLabel26);
        jLabel26.setBounds(126, 140, 320, 14);

        panelGlass5.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass5.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/logo_rsud.jpg"))); // NOI18N
        panelGlass5.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass5.setRound(false);
        panelGlass5.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass5.setLayout(null);

        panelGlass6.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass6.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass6.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass6.setRound(false);
        panelGlass6.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass6.setLayout(null);
        panelGlass5.add(panelGlass6);
        panelGlass6.setBounds(10, 380, 250, 60);

        panelGlass7.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass7.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass7.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass7.setRound(false);
        panelGlass7.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass7.setLayout(null);

        panelGlass8.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass8.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass8.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass8.setRound(false);
        panelGlass8.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass8.setLayout(null);
        panelGlass7.add(panelGlass8);
        panelGlass8.setBounds(10, 380, 250, 60);

        panelGlass5.add(panelGlass7);
        panelGlass7.setBounds(70, 330, 250, 60);

        panelGlass4.add(panelGlass5);
        panelGlass5.setBounds(190, 380, 50, 50);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Close");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setIconTextGap(3);
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass4.add(BtnKeluar);
        BtnKeluar.setBounds(350, 410, 100, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(50, 50, 50));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Dikembangkan bersama : TIM PIT RSUD MERAUKE");
        jLabel27.setName("jLabel27"); // NOI18N
        panelGlass4.add(jLabel27);
        jLabel27.setBounds(20, 350, 420, 14);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(50, 50, 50));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("atas nama Windiarto");
        jLabel28.setName("jLabel28"); // NOI18N
        panelGlass4.add(jLabel28);
        jLabel28.setBounds(16, 260, 420, 14);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(50, 50, 50));
        jLabel31.setText("08562675039     Pengembang : Windiarto Nugroho, Dewi Ekawati, YASKI dll");
        jLabel31.setName("jLabel31"); // NOI18N
        panelGlass4.add(jLabel31);
        jLabel31.setBounds(58, 10, 420, 14);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(50, 50, 50));
        jLabel32.setText("elkhanza.wordpress.com, simrskhanza.weebly.com, yaski.or.id");
        jLabel32.setName("jLabel32"); // NOI18N
        panelGlass4.add(jLabel32);
        jLabel32.setBounds(58, 30, 430, 14);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(50, 50, 50));
        jLabel33.setText("khanza_media@yahoo.com, khanzasoftmedia@gmail.com");
        jLabel33.setName("jLabel33"); // NOI18N
        panelGlass4.add(jLabel33);
        jLabel33.setBounds(58, 50, 420, 14);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(50, 50, 50));
        jLabel34.setText("github.com/mas-elkhanza     Instagram : simrskhanza");
        jLabel34.setName("jLabel34"); // NOI18N
        panelGlass4.add(jLabel34);
        jLabel34.setBounds(58, 70, 420, 14);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(50, 50, 50));
        jLabel35.setText("RS Haji Kamino Way Kanan, RS PKU Jatinom Klaten, RS Khalisah,");
        jLabel35.setName("jLabel35"); // NOI18N
        panelGlass4.add(jLabel35);
        jLabel35.setBounds(126, 180, 320, 14);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(50, 50, 50));
        jLabel36.setText("RS Alam Medica Bumiayu, dll");
        jLabel36.setName("jLabel36"); // NOI18N
        panelGlass4.add(jLabel36);
        jLabel36.setBounds(126, 200, 320, 14);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(50, 50, 50));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Bagi yang ingin melakukan Donasi, bisa ke Rekening BSI 1015369872, kode bank 451");
        jLabel37.setName("jLabel37"); // NOI18N
        panelGlass4.add(jLabel37);
        jLabel37.setBounds(16, 240, 420, 14);

        panelGlass9.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass9.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass9.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass9.setRound(false);
        panelGlass9.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass9.setLayout(null);

        panelGlass10.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass10.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass10.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass10.setRound(false);
        panelGlass10.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass10.setLayout(null);
        panelGlass9.add(panelGlass10);
        panelGlass10.setBounds(10, 380, 250, 60);

        panelGlass11.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass11.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass11.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass11.setRound(false);
        panelGlass11.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass11.setLayout(null);

        panelGlass12.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass12.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass12.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass12.setRound(false);
        panelGlass12.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass12.setLayout(null);
        panelGlass11.add(panelGlass12);
        panelGlass12.setBounds(10, 380, 250, 60);

        panelGlass9.add(panelGlass11);
        panelGlass11.setBounds(70, 330, 250, 60);

        panelGlass4.add(panelGlass9);
        panelGlass9.setBounds(0, 380, 180, 50);

        internalFrame1.add(panelGlass4);
        panelGlass4.setBounds(10, 50, 454, 440);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        dispose();
}//GEN-LAST:event_BtnKeluarKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgAbout dialog = new DlgAbout(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private usu.widget.glass.PanelGlass panelGlass10;
    private usu.widget.glass.PanelGlass panelGlass11;
    private usu.widget.glass.PanelGlass panelGlass12;
    private usu.widget.glass.PanelGlass panelGlass4;
    private usu.widget.glass.PanelGlass panelGlass5;
    private usu.widget.glass.PanelGlass panelGlass6;
    private usu.widget.glass.PanelGlass panelGlass7;
    private usu.widget.glass.PanelGlass panelGlass8;
    private usu.widget.glass.PanelGlass panelGlass9;
    // End of variables declaration//GEN-END:variables

}
